export const COLORS = {
    BLACK_TEXT: "#000000",
    WHITE_TEXT: "#FFFFFF",
    HEADER_BACKGROUND: "#D9D9D9",
    FOOTER_BACKGROUND: "#E9E9E9",
    BUTTON_BACKGROUND: "#6e6e6e",
    HOME_BACKGROUND: "#E6E6E6"
}

